### ISSUE TITLE
Doesn't work with node > v12

### ISSUE THREAD

**Issue by pbadenski** [wasm-tool/node-loader#9]
I tried on v12.16.0, v13.14.0 and v14.2.0

Getting error below:

```
TypeError [ERR_INVALID_URL]: Invalid URL: [object Object]
    at onParseError (internal/url.js:257:9)
    at new URL (internal/url.js:333:5)
    at new URL (internal/url.js:330:22)
    at resolve (file:///Users/pbadenski/workspace/pricingmonkey/app/node_modules/@wasm-tool/node/loader.mjs:56:12)
    at Loader.resolve (internal/modules/esm/loader.js:85:40)
    at Loader.getModuleJob (internal/modules/esm/loader.js:188:40)
    at ModuleWrap.<anonymous> (internal/modules/esm/module_job.js:42:40)
    at link (internal/modules/esm/module_job.js:41:36) {
  input: '[object Object]',
  code: 'ERR_INVALID_URL'
}
```

**Comment by xtuc** [comment]
I suspect that  the node ESM integration changed a bit since.
